image: alpine:3

stages:
  - test
  - install

before_script:
  - apk update
  - apk add bash make shellcheck

test:
  stage: test
  script:
    - make test

install:
  stage: install
  script:
    - make install
    - nf
    - make uninstall
