image: alpine:3

stages:
  - dev

before_script:
  - apk update
  - apk add bash make shellcheck

test:
  stage: dev
  script:
    - make test
    - make install
    - nf --travis -v
    - make uninstall 
