image: alpine:3

stages:
  - test
  - install
  - run
  - uninstall

before_script:
  - apk update
  - apk add bash make shellcheck

test:
  stage: test
  script:
    - make test

install:
  stage: install
  script:
    - make install

run:
  stage: run
  script:
    - nf

uninstall:
  stage: uninstall
  script:
    - make uninstall 
